name: App infrastructure deployment

on:
  workflow_run:
    workflows: ["Terraform Apply"]   # The name of the first workflow
    types:
      - completed

jobs:
  terraform:
    # if: startsWith(github.event.head_commit.message, 'terraform apply')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webApp
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.6

    - name: Terraform Init & Apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        terraform init
        terraform apply --auto-approve