name: Terraform Apply

on:
  push:
    branches: [main]

jobs:
  Bucket:
    # if: startsWith(github.event.head_commit.message, 'terraform apply')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.6

    - name: Terraform Init & Apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        terraform init
        terraform apply --auto-approve
  
  ApplyWebApp:

    # if: startsWith(github.event.head_commit.message, 'terraform apply')
    runs-on: ubuntu-latest
    needs: 
      - Bucket
    # This job will only run after the Bucket job has completed successfully
    defaults:
      run:
        working-directory: webApp
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.6

    - name: Terraform Init & Apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        terraform init
        terraform apply --auto-approve